---
- name: Configure web server and install K3s
  hosts: myvms
  become: yes
  tasks:
    - name: Ensure APT cache is up to date
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        update_cache_retries: 5

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Enable and start Apache2 service
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Install required packages for K3s
      ansible.builtin.apt:
        name:
          - curl
          - iptables
          - socat
          - conntrack
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Install K3s server without starting the service
      ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true K3S_OPTIONS="--cgroup-driver=cgroupfs" sh -
      args:
        creates: /usr/local/bin/k3s
      register: k3s_install_result

    - name: Pause for a few seconds to let systemd register the service
      ansible.builtin.pause:
        seconds: 5

    - name: Ensure K3s service is running and enabled
      ansible.builtin.systemd:
        name: k3s
        state: started
        enabled: yes
