teleport_version: "18.2.4"
teleport_user: "exploravisuser"
teleport_host: "teleport.exploravis.ddns.net"
teleport_token: "devtoken"
teleport_data_dir: "/var/lib/teleport"
teleport_log: "/var/log/teleport.log"
teleport_cfg: "/etc/teleport.yaml"  
github_org: "Exploravis"
github_team: "ea-team"
github_client_id: "{{ lookup('env', 'EA_GITHUB_CLIENT_ID') }}"
github_client_secret: "{{ lookup('env', 'EA_GITHUB_CLIENT_SECRET') }}"
github_infra_repo: "Exploravis/exploravis-infra-configs"
github_infra_repo_workflows: ".github/workflows/teleport-test.yaml"
