---
- name: install K3s
  hosts: master 
  become: yes
  tasks:
    - name: Ensure APT cache is up to date
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        update_cache_retries: 5

    - name: Install required packages for K3s
      ansible.builtin.apt:
        name:
          - curl
          - iptables
          - socat
          - conntrack
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Install K3s server without starting the service
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -

      args:
        creates: /usr/local/bin/k3s
      register: k3s_install_result
    - name: Get node token
      slurp: 
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
    - name: Set token fact
      set_fact:
        k3s_token: "{{ node_token['content'] | b64decode | trim }}"


    - name: Ensure K3s service is running and enabled
      ansible.builtin.systemd:
        name: k3s
        state: started
        enabled: yes

- name: Setup k3s workers 
  hosts: workers
  become: true
  vars:
    k3s_master_ip: "{{hostvars['master']['ansible_host']}}"
  tasks:
    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ hostvars['master']['k3s_token'] }} sh -
