---
- name: install K3s
  hosts: master 
  become: yes
  tasks:
    - name: Ensure APT cache is up to date
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        update_cache_retries: 5

    - name: Install required packages for K3s
      ansible.builtin.apt:
        name:
          - curl
          - iptables
          - socat
          - conntrack
          - ca-certificates
          - gnupg
          - jq 
          - openssl
        state: present
        update_cache: yes

    - name: Install K3s server 
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      register: k3s_install_result

    - name: Disable traefik after installation
      ansible.builtin.shell: |
        sudo kubectl delete -n kube-system helmchart traefik
      when: k3s_install_result.changed
      failed_when: false

    - name: Get node token
      slurp: 
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
    - name: Set token fact
      set_fact:
        k3s_token: "{{ node_token['content'] | b64decode | trim }}"


    - name: Ensure K3s service is running and enabled
      ansible.builtin.systemd:
        name: k3s
        state: started
        enabled: yes

    # - name: Add Teleport repo
    #   ansible.builtin.shell: |
    #     curl https://apt.releases.teleport.dev/gpg | gpg --dearmor | tee /usr/share/keyrings/teleport-archive-keyring.gpg > /dev/null
    #     echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.gpg] https://apt.releases.teleport.dev/stable/debian $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/teleport.list
    #
    # - name: Install Teleport
    #   ansible.builtin.apt:
    #     name: teleport
    #     state: present
    #     update_cache: yes
    #
    # - name: Enable and start Teleport
    #   ansible.builtin.systemd:
    #     name: teleport
    #     enabled: yes
    #     state: started

- name: Setup k3s workers 
  hosts: workers
  become: true
  vars:
    # k3s_master_ip: "{{hostvars['master']['ansible_host']}}"
    k3s_master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"

  tasks:
    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token'] }} sh -
