- name: Deploy Teleport main configuration template
  ansible.builtin.template:
    src: templates/teleport.yaml.j2
    dest: "{{ teleport_cfg }}"
    mode: '0644'

- name: Deploy GitHub connector configuration template
  ansible.builtin.template:
    src: templates/github-connector.yaml.j2
    dest: /etc/teleport/github.yaml
    mode: '0644'

